export const paletteFiles = [
    ["resurrect-64.pal", "Kerrie Lake", "https://lospec.com/palette-list/resurrect-64"],
    ["aap-64.pal", "Adigun A. Polack", "https://lospec.com/palette-list/aap-64"],
    ["ammo-8.pal", "rsvp asap", "https://lospec.com/palette-list/ammo-8"],
    ["pico-8.pal", "Lexaloffle Games", "https://lospec.com/palette-list/pico-8"],
    ["slso8.pal", "Luis Miguel Maldonado", "https://lospec.com/palette-list/slso8"],
    ["sweetie-16.pal", "GrafxKid", "https://lospec.com/palette-list/sweetie-16"],
    ["lost-century.pal", "SurrealEmber", "https://lospec.com/palette-list/lost-century"],
    ["hollow.pal", "Poltergasm", "http://lospec.com/palette-list/hollow"],
    ["ice-cream-gb.pal", "Kerrie Lake", "https://lospec.com/palette-list/ice-cream-gb"],
    ["chocomilk-8.pal", "Blylzz", "https://lospec.com/palette-list/chocomilk-8"],
    ["eulbink.pal", "Inkpendude", "https://lospec.com/palette-list/eulbink"],
    ["inkpink.pal", "Inkpendude", "https://lospec.com/inkpendude"],
    ["funkyfuture-8.pal", "Shamaboy", "https://lospec.com/palette-list/funkyfuture-8"],
    ["steam-lords.pal", "Slynyrd", "https://lospec.com/palette-list/steam-lords"],
    ["wplace.pal", "wplace", "https://wplace.live/"],
    ["pikusere-9.pal", "adamadamode", "https://x.com/adamadamode"],
];
// ["","",""],

// ["midnight-ablaze.pal", "Inkpendude", "https://lospec.com/palette-list/midnight-ablaze"],
// ["blessing.pal", "まるき", "https://lospec.com/palette-list/blessing"],
// ["cl8uds.pal", "_Nicola", "https://lospec.com/palette-list/cl8uds"],
